Entity/Offer.php
<?php

declare(strict_types=1);

namespace Ekyna\Bundle\ProductBundle\Entity;

use Decimal\Decimal;
use Ekyna\Bundle\ProductBundle\Exception\InvalidArgumentException;
use Ekyna\Bundle\ProductBundle\Model;
use Ekyna\Bundle\ProductBundle\Model\OfferInterface;
use Ekyna\Component\Commerce\Common\Model\CountryInterface;
use Ekyna\Component\Commerce\Customer\Model\CustomerGroupInterface;
use Ekyna\Component\Resource\Model\AbstractResource;

/**
 * Class Offer
 * @package Ekyna\Bundle\ProductBundle\Entity
 * @author  Étienne Dauvergne <contact@ekyna.com>
 */
class Offer extends AbstractResource implements OfferInterface
{
    private Decimal                      $minQuantity;
    private Decimal                      $percent;
    private Decimal                      $netPrice;
    /** @var array<string, string> */
    private array                        $details      = [];
    private ?Model\ProductInterface      $product      = null;
    private ?CustomerGroupInterface      $group        = null;
    private ?CountryInterface            $country      = null;
    private ?Model\SpecialOfferInterface $specialOffer = null;
    private ?Model\PricingInterface      $pricing      = null;

    public function __construct()
    {
        $this->minQuantity = new Decimal(0);
        $this->percent = new Decimal(0);
        $this->netPrice = new Decimal(0);
    }

    public function getMinQuantity(): Decimal
    {
        return $this->minQuantity;
    }

    public function setMinQuantity(Decimal $quantity): OfferInterface
    {
        $this->minQuantity = $quantity;

        return $this;
    }

    public function getPercent(): Decimal
    {
        return $this->percent;
    }

    public function setPercent(Decimal $percent): OfferInterface
    {
        $this->percent = $percent;

        return $this;
    }

    public function getNetPrice(): Decimal
    {
        return $this->netPrice;
    }

    public function setNetPrice(Decimal $amount): OfferInterface
    {
        $this->netPrice = $amount;

        return $this;
    }

    public function getDetails(): array
    {
        return $this->details;
    }

    public function setDetails(array $details): OfferInterface
    {
        foreach ($details as $type => $percent) {
            $this->addDetails($type, $percent);
        }

        return $this;
    }

    public function addDetails(string $type, Decimal $percent): OfferInterface
    {
        if (!in_array($type, [OfferInterface::TYPE_PRICING, OfferInterface::TYPE_SPECIAL], true)) {
            throw new InvalidArgumentException('Unexpected offer type');
        }

        $this->details[$type] = $percent->toFixed(2);

        return $this;
    }

    public function getProduct(): ?Model\ProductInterface
    {
        return $this->product;
    }

    public function setProduct(?Model\ProductInterface $product): OfferInterface
    {
        $this->product = $product;

        return $this;
    }

    public function getGroup(): ?CustomerGroupInterface
    {
        return $this->group;
    }

    public function setGroup(?CustomerGroupInterface $group): OfferInterface
    {
        $this->group = $group;

        return $this;
    }

    public function getCountry(): ?CountryInterface
    {
        return $this->country;
    }

    public function setCountry(?CountryInterface $country): OfferInterface
    {
        $this->country = $country;

        return $this;
    }

    public function getSpecialOffer(): ?Model\SpecialOfferInterface
    {
        return $this->specialOffer;
    }

    public function setSpecialOffer(?Model\SpecialOfferInterface $specialOffer): OfferInterface
    {
        $this->specialOffer = $specialOffer;

        return $this;
    }

    public function getPricing(): ?Model\PricingInterface
    {
        return $this->pricing;
    }

    public function setPricing(?Model\PricingInterface $pricing): OfferInterface
    {
        $this->pricing = $pricing;

        return $this;
    }

    public function getDetailedPercents(): array
    {
        $percents = [];

        foreach ([OfferInterface::TYPE_SPECIAL, OfferInterface::TYPE_PRICING] as $type) {
            if (isset($this->details[$type])) {
                $percents[] = $this->details[$type];
            }
        }

        return $percents;
    }
}

Form/Type/ProductType.php
<?php

declare(strict_types=1);

namespace Ekyna\Bundle\ProductBundle\Form\Type;

use Ekyna\Bundle\ProductBundle\Form\EventListener\ProductTypeSubscriber;
use Ekyna\Bundle\ProductBundle\Model\ProductInterface;
use Ekyna\Bundle\ResourceBundle\Form\Type\AbstractResourceType;
use RuntimeException;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use function strlen;

/**
 * Class ProductType
 * @package Ekyna\Bundle\ProductBundle\Form\Type
 * @author  Etienne Dauvergne <contact@ekyna.com>
 */
class ProductType extends AbstractResourceType
{
    private ProductTypeSubscriber $subscriber;

    public function __construct(ProductTypeSubscriber $subscriber)
    {
        $this->subscriber = $subscriber;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->addEventSubscriber($this->subscriber);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver);

        $resolver->setDefaults([
            'validation_groups' => function (FormInterface $form) {
                /** @var ProductInterface $product */
                $product = $form->getData();

                if (!strlen($product->getType())) {
                    throw new RuntimeException('Product type is not set.');
                }

                return ['Default', $product->getType()];
            },
        ]);
    }
}

Controller/Account/ProductController.php
<?php

declare(strict_types=1);

namespace Ekyna\Bundle\ProductBundle\Controller\Account;

use Ekyna\Bundle\ProductBundle\Exception\UnexpectedTypeException;
use Ekyna\Bundle\ProductBundle\Service\Search\ProductRepository;
use Ekyna\Component\Resource\Search\Request as SearchRequest;
use Ekyna\Component\Resource\Search\Search;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

/**
 * Class ProductController
 * @package Ekyna\Bundle\ProductBundle\Controller\Account
 * @author  Etienne Dauvergne <contact@ekyna.com>
 */
class ProductController
{
    private AuthorizationCheckerInterface $authorization;
    private Search                        $search;

    public function __construct(
        AuthorizationCheckerInterface $authorization,
        Search                        $search
    ) {
        $this->authorization = $authorization;
        $this->search = $search;
    }

    public function search(Request $request): Response
    {
        if (!$this->authorization->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            throw new AccessDeniedHttpException();
        }

        $repository = $this->search->getRepository('ekyna_product.product');
        if (!$repository instanceof ProductRepository) {
            throw new UnexpectedTypeException($repository, ProductRepository::class);
        }

        $page = $request->query->getInt('page', 1) - 1;
        $limit = $request->query->getInt('limit', 10);
        $expression = (string)$request->query->get('query');

        $searchRequest = new SearchRequest($expression);
        $searchRequest
            ->setType(SearchRequest::RAW)
            ->setLimit($limit)
            ->setOffset($page * $limit)
            ->setParameter('types', (array)$request->query->get('types', []));

        if (!$repository->supports($searchRequest)) {
            return new JsonResponse([
                'results'     => [],
                'total_count' => 0,
            ]);
        }

        return new JsonResponse($repository->search($searchRequest));
    }
}

Controller/Test/ProductController.php
<?php

namespace Ekyna\Bundle\ProductBundle\Controller\Test;

use Ekyna\Bundle\CoreBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class ProductController
 * @package Ekyna\Bundle\ProductBundle\Controller\Test
 * @author  Etienne Dauvergne <contact@ekyna.com>
 */
class ProductController extends Controller
{
    /**
     * Product detail action.
     *
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function detailAction(Request $request)
    {
        /** @var \Ekyna\Bundle\ProductBundle\Entity\Product $product */
        $product = $this
            ->get('ekyna_product.repository.product')
            ->findOneByReference($request->attributes->get('reference'));

        if (null === $product) {
            throw $this->createNotFoundException("Product not found.");
        }

        // Add to cart form
        $cartHelper = $this->get('ekyna_commerce.cart_helper');
        $form = $cartHelper
            ->createAddSubjectToCartForm($product, [
                'extended'      => false,
                'submit_button' => true,
            ]);

        if (null !== $event = $cartHelper->handleAddSubjectToCartForm($form, $request)) {
            $this->addFlash($event->getMessage(), 'info');

            return $this->redirectToRoute('ekyna_product_front_product_detail', [
                'reference' => $product->getReference(),
            ]);
        }

        // TODO Resource locale switcher

        $view = $form->createView();

        return $this->render('@EkynaProduct/Test/Product/detail.html.twig', [
            'product' => $product,
            'form'    => $view,
        ]);
    }

    public function dumpAction($productId)
    {
        /** @var \Ekyna\Bundle\ProductBundle\Entity\Product $product */
        $product = $this->get('ekyna_product.repository.product')->find($productId);

        if (null === $product) {
            throw $this->createNotFoundException("Product not found.");
        }

        return $this->render('@EkynaProduct/Test/Product/dump.html.twig', [
            'product' => $product,
        ]);
    }
}

Resources/views/Admin/Product/Show/_offers.html.twig
{% apply spaceless %}
<hr>
{{- admin_resource_btn(product, 'Ekyna\\Bundle\\ProductBundle\\Action\\Admin\\Product\\InvalidateOffersAction', {
    'theme': 'primary',
    'size': 'sm'
}, {
    'class': ('pull-right' ~ (product.pendingOffers ? ' disabled' : ''))
}) -}}
<h3>{{ 'offer.label.plural'|trans({}, 'EkynaProduct') }}</h3>
<div class="show-product-offers">
{% for list in product|product_offer_list %}
    {% if loop.index0 % 3 == 0 %}
    <div class="row">
    {% endif %}
        <div class="col-sm-12 col-md-4">
            <div class="offers-list">
                <p class="h5">{{ list.title }}</p>
                <table class="table table-condensed table-alt-head">
                    <tr>
                        <th>Qty. Min.</th>
                        <th>Percent</th>
                        <th>Net price</th>
                        <th>&nbsp;</th>
                    </tr>
                    {% for offer in list.offers %}
                    <tr>
                        <td>{{ offer.minQuantity|format_number }}</td>
                        <td>
                            <strong>{{ offer.percent|format_number }}&nbsp;%</strong>
                            ({%- for percent in offer.detailedPercents -%}
                                {{ percent|format_number }}&nbsp;%{% if not loop.last %},&nbsp;{% endif -%}
                            {%- endfor -%})
                        </td>
                        <td>
                            <strong class="text-primary">{{ offer.netPrice|format_currency(commerce_default_currency) }}</strong>
                        </td>
                        <td>
                        {% if offer.specialOffer is not null -%}
                        {% if offer.specialOffer.product is null -%}
                            <a href="{{ admin_resource_path(offer.specialOffer) }}"
                               class="btn btn-xs btn-primary"
                               title="{{ 'special_offer.label.singular'|trans({}, 'EkynaProduct') }}">
                                <i class="fa fa-arrow-right"></i>
                            </a>
                        {% endif -%}
                        {% endif -%}
                        {% if offer.pricing is not null -%}
                        {% if offer.pricing.product is null -%}
                        <a href="{{ admin_resource_path(offer.pricing) }}"
                           class="btn btn-xs btn-default"
                            title="{{ 'pricing.label.singular'|trans({}, 'EkynaProduct') }}">
                            <i class="fa fa-arrow-right"></i>
                        </a>
                        {%- endif %}
                        {%- endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    {% if loop.last or loop.index % 3 == 0 %}
    </div>
    {% endif %}
{% else %}
    <p><em>{{ 'product.alert.no_offer'|trans({}, 'EkynaProduct') }}</em></p>
{% endfor %}
</div>
{% endapply %}

Resources/views/Admin/Product/Show/_prices.html.twig
{% apply spaceless %}
<hr>
<h3>{{ 'price.label.plural'|trans({}, 'EkynaProduct') }}</h3>
<div class="show-product-offers">
{% for list in product|product_price_list %}
    {% if loop.index0 % 3 == 0 %}
    <div class="row">
    {% endif %}
        <div class="col-sm-12 col-md-4">
            <div class="prices-list">
                <p class="h5">{{ list.title }}</p>
                <table class="table table-condensed table-alt-head">
                    <tr>
                        <th>Percent</th>
                        <th>Net price</th>
                    </tr>
                    {% for price in list.prices %}
                    <tr>
                        <td>
                            <strong>{{ price.percent|format_number }}&nbsp;%</strong>
                            ({%- for percent in price.detailedPercents -%}
                                {{ percent|format_number }}&nbsp;%{% if not loop.last %},&nbsp;{% endif -%}
                            {%- endfor -%})
                        </td>
                        <td>
                            {% if price.originalPrice > price.sellPrice %}
                                <del>{{ price.originalPrice|format_currency(commerce_default_currency) }}</del>&nbsp;
                            {% endif %}
                            <strong class="text-primary">{{ price.sellPrice|format_currency(commerce_default_currency) }}</strong>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    {% if loop.last or loop.index % 3 == 0 %}
    </div>
    {% endif %}
{% else %}
    <p><em>{{ 'product.alert.no_price'|trans({}, 'EkynaProduct') }}</em></p>
{% endfor %}
</div>
{% endapply %}

Resources/views/Admin/Product/Show/base.html.twig
{% import '@EkynaProduct/Admin/Product/Show/_macro.html.twig' as _product %}

{% set optionParents = product|option_parents %}
{% set componentParents = product|component_parents %}
{% set bundleParents = product|bundle_parents %}

<div class="show show-with-tabs">
    <ul class="nav nav-tabs" data-tab-key="{{ resource_name }}">
        <li class="active">
            <a href="#{{ resource_name }}-general" id="toggle-product-general" data-toggle="tab">
                {{ 'field.general'|trans({}, 'EkynaUi') }}
            </a>
        </li>

        {%- block content_tab -%}
        <li>
            <a href="#{{ resource_name }}-content" id="toggle-product-content" data-toggle="tab">
                {{- 'field.content'|trans({}, 'EkynaUi') -}}
            </a>
        </li>
        {%- endblock content_tab -%}

        {%- block pricing_tab -%}
        <li>
            <a href="#{{ resource_name }}-pricing" id="toggle-product-pricing" data-toggle="tab">
                {{- 'product.field.pricing'|trans({}, 'EkynaProduct') -}}
            </a>
        </li>
        {%- endblock pricing_tab -%}

        {%- block offers_tab -%}
        <li>
            <a href="#{{ resource_name }}-offers" id="toggle-product-offers" data-toggle="tab">
                {{- 'offer.label.plural'|trans({}, 'EkynaProduct') -}}
            </a>
        </li>
        {%- endblock offers_tab -%}

        {%- block stock_tab -%}
        <li>
            <a href="#{{ resource_name }}-stock" id="toggle-product-stock" data-toggle="tab">
                {{- 'product.field.stock'|trans({}, 'EkynaProduct') -}}
            </a>
        </li>
        {%- endblock stock_tab -%}

        {%- block relations_tab -%}
        {%- if optionParents is not empty or componentParents is not empty or bundleParents is not empty -%}
        <li>
            <a href="#{{ resource_name }}-relations" id="toggle-product-relations" data-toggle="tab">
                {{ 'product.field.relations'|trans({}, 'EkynaProduct') }}
            </a>
        </li>
        {%- endif -%}
        {%- endblock relations_tab -%}

        {%- if product is child_product -%}
        {%- block suppliers_tab -%}
        <li>
            <a href="#{{ resource_name }}-suppliers" id="toggle-product-suppliers" data-toggle="tab">
                {{ 'supplier.label.plural'|trans({}, 'EkynaCommerce') }}
            </a>
        </li>
        {%- endblock suppliers_tab -%}
        {%- endif -%}

        {%- block stat_tab -%}
        <li>
            <a href="#{{ resource_name }}-stat" id="toggle-product-stat" data-toggle="tab">
                {{ 'stat.label'|trans({}, 'EkynaProduct') }}
            </a>
        </li>
        {%- endblock stat_tab -%}

        {%- block seo_tab -%}
        <li>
            <a href="#{{ resource_name }}-seo" id="toggle-product-seo" data-toggle="tab">
                {{ 'field.seo'|trans({}, 'EkynaUi') }}
            </a>
        </li>
        {%- endblock seo_tab -%}
        {% for tab in extra_tabs -%}
        <li>
            <a href="#{{ resource_name }}-{{ tab.id }}" id="toggle-{{ tab.id }}" data-toggle="tab">
                {{ tab.title|trans }}
            </a>
        </li>
        {%- endfor %}
    </ul>
    <div class="show-body">
        <div class="tab-content">
            <div class="tab-pane active" id="{{ resource_name }}-general">
            {%- block general_content -%}
                {{ _product.show_designation(product) }}
            {%- endblock general_content -%}
            </div>

            {%- block content_pane -%}
                <div class="tab-pane" id="{{ resource_name }}-content">
                {%- block content_content -%}
                    {{ _product.show_translations(product) }}
                    {{ _product.show_medias(product) }}
                    {{ _product.show_not_contractual(product) }}
                    <div class="row">
                        <div class="col-md-4">
                            {{ _product.show_internal_manual(product, {'label_col': 6}) }}
                        </div>
                        <div class="col-md-8">
                            {{ _product.show_external_manual(product, {'label_col': 3}) }}
                        </div>
                    </div>
                {%- endblock content_content -%}
                </div>
            {%- endblock content_pane -%}

            {%- block pricing_pane -%}
                <div class="tab-pane" id="{{ resource_name }}-pricing">
                {%- block pricing_content -%}
                    <div class="row">
                        <div class="col-md-4">
                            {{ _product.show_reference(product, {'label_col': 6}) }}
                        </div>
                        <div class="col-md-4">
                            {{ _product.show_net_price(product, {'label_col': 6}) }}
                        </div>
                        <div class="col-md-4">
                            {{ _product.show_tax_group(product, {'label_col': 6}) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{ _product.show_min_price(product, {'label_col': 6}) }}
                        </div>
                    </div>
                {%- endblock pricing_content -%}
                {%- if product_feature('component') and product is variable_product -%}{# TODO (?) or product is bundle_product #}
                {{ _product.show_components(product) }}
                {%- endif -%}
                {{ _product.show_option_groups(product) }}
                </div>
            {%- endblock pricing_pane -%}

            {%- block offers_pane -%}
            <div class="tab-pane" id="{{ resource_name }}-offers">
                {% block offers_content -%}
                {% if product is simple_product or product is variant_product or product is bundle_product -%}
                {{ _product.show_pricing_group(product) }}
                {{ _product.show_special_offers(product) }}
                {{ _product.show_pricings(product) }}
                {%- endif %}
                {% include '@EkynaProduct/Admin/Product/Show/_offers.html.twig' %}
                {% include '@EkynaProduct/Admin/Product/Show/_prices.html.twig' %}
                {%- endblock offers_content %}
            </div>
            {%- endblock offers_pane -%}

            {%- block stock_pane -%}
            <div class="tab-pane" id="{{ resource_name }}-stock">
            {%- block stock_content -%}
                <p class="actions">
                    {%- block stock_actions -%}
                    {{ admin_resource_btn(product, 'Ekyna\\Bundle\\CommerceBundle\\Action\\Admin\\Subject\\RefreshStockAction', {
                        'label': 'button.reload',
                        'trans_domain': 'EkynaUi',
                        'type': 'link',
                        'icon': 'refresh'
                    }, {
                        'id': 'stock-view-refresh'
                    }) }}
                    {%- endblock stock_actions -%}
                </p>
                <div id="stock-view">
                    {{ render_subject_stock_view(product, {'prefix': 'product'}) }}
                </div>
            {%- endblock stock_content -%}
            </div>
            {%- endblock stock_pane -%}

            {%- block relations_pane -%}
            {%- if optionParents is not empty or componentParents is not empty or bundleParents is not empty -%}
            <div class="tab-pane" id="{{ resource_name }}-relations">
            {%- block relations_content -%}
                {% if bundleParents is not empty -%}
                    <p class="h4">{{ 'product.field.bundle_parents'|trans({}, 'EkynaProduct') }}</p>
                    {{ _product.show_relations(bundleParents) }}
                {%- endif %}
                {% if componentParents is not empty -%}
                    <p class="h4">{{ 'product.field.component_parents'|trans({}, 'EkynaProduct') }}</p>
                    {{ _product.show_relations(componentParents) }}
                {%- endif %}
                {% if optionParents is not empty -%}
                    <p class="h4">{{ 'product.field.option_parents'|trans({}, 'EkynaProduct') }}</p>
                    {{ _product.show_relations(optionParents) }}
                {%- endif %}
            {%- endblock relations_content -%}
            </div>
            {%- endif -%}
            {%- endblock relations_pane -%}

            {%- if product is child_product -%}
            {%- block suppliers_pane -%}
            <div class="tab-pane" id="{{ resource_name }}-suppliers">
                {% block suppliers_content -%}
                {% set form = (product|subject_create_supplier_product_form).createView() %}
                <div style="text-align: right">
                    {{ bootstrap_set_sizing('sm') }}
                    {{ form_start(form, { 'style': 'inline' }) }}
                    {{ form_row(form.supplier) }}
                    {{ form_widget(form.submit) }}
                    {{ form_end(form) }}
                    {{ bootstrap_set_sizing('md') }}
                </div>
                <hr>
                {{ ekyna_table_render(admin_resource_table('ekyna_commerce.supplier_product', {
                    'subject': product
                })) }}
                {%- endblock suppliers_content %}
            </div>
            {%- endblock suppliers_pane -%}
            {%- endif -%}

            {%- block stat_pane -%}
            <div class="tab-pane" id="{{ resource_name }}-stat">
            {%- block stat_content -%}
                {{ _product.show_stat_charts(product) }}
            {%- endblock stat_content -%}
            </div>
            {%- endblock stat_pane -%}

            {%- block seo_pane -%}
            <div class="tab-pane" id="{{ resource_name }}-seo">
            {%- block seo_content -%}
                {{ _product.show_seo(product) }}
            {%- endblock seo_content -%}
            </div>
            {%- endblock seo_pane -%}

            {% for tab in extra_tabs -%}
            <div class="tab-pane" id="{{ resource_name }}-{{ tab.id }}">
                {% include tab.template with tab.data only %}
            </div>
            {%- endfor %}
        </div>
    </div>
</div>
{%- block children_content %}{% endblock children_content -%}

Resources/views/Admin/Product/Show/bundle.html.twig
{% extends '@EkynaProduct/Admin/Product/Show/base.html.twig' %}


{% import '@EkynaProduct/Admin/Product/Show/_macro.html.twig' as _product %}


{% block pricing_tab %}
    <li>
        <a href="#{{ resource_name }}-pricing" id="toggle-product-pricing" data-toggle="tab">
            {{- 'product.field.composition'|trans({}, 'EkynaProduct') -}}
        </a>
    </li>
{% endblock pricing_tab %}

{% block general_content %}
    {{ parent() }}
    {{ _product.show_categories(product) }}
    <div class="row">
        <div class="col-md-6">
            {{ _product.show_brand(product, {'label_col': 4}) }}
        </div>
        <div class="col-md-6">
            {{ _product.show_brandNaming(product, {'label_col': 4}) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ _product.show_visible(product, {'label_col': 4}) }}
        </div>
        <div class="col-md-6">
            {{ _product.show_visibility(product, {'label_col': 4}) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ _product.show_best_seller(product, {'label_col': 4}) }}
        </div>
        <div class="col-md-6">
            {{ _product.show_cross_selling(product, {'label_col': 4}) }}
        </div>
    </div>
    {{ _product.show_cross_sellings(product) }}
{% endblock general_content %}


{% block pricing_content %}
    {{ parent() }}
    {{ _product.show_references(product) }}
    {{ _product.show_bundle_composition(product) }}
{% endblock pricing_content %}


{%- block stock_actions -%}
    {{ admin_resource_btn(product, 'Ekyna\\Bundle\\ProductBundle\\Action\\Admin\\Product\\AdjustStockAction') }}
    {{ parent() }}
{%- endblock stock_actions -%}

Resources/views/Admin/Product/Show/configurable.html.twig
{% extends '@EkynaProduct/Admin/Product/Show/base.html.twig' %}


{% import '@EkynaProduct/Admin/Product/Show/_macro.html.twig' as _product %}


{% block pricing_tab %}
    <li>
        <a href="#product-pricing" id="toggle-product-pricing" data-toggle="tab">
            {{- 'product.field.composition'|trans({}, 'EkynaProduct') -}}
        </a>
    </li>
{% endblock pricing_tab %}


{% block general_content %}
    {{ parent() }}
    {{ _product.show_categories(product) }}
    <div class="row">
        <div class="col-md-6">
            {{ _product.show_brand(product, {'label_col': 4}) }}
        </div>
        <div class="col-md-6">
            {{ _product.show_brandNaming(product, {'label_col': 4}) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ _product.show_visible(product, {'label_col': 4}) }}
        </div>
        <div class="col-md-6">
            {{ _product.show_visibility(product, {'label_col': 4}) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {{ _product.show_best_seller(product, {'label_col': 4}) }}
        </div>
        <div class="col-md-6">
            {{ _product.show_cross_selling(product, {'label_col': 4}) }}
        </div>
    </div>
    {{ _product.show_cross_sellings(product) }}
{% endblock general_content %}


{% block pricing_content %}
    {{ parent() }}
    {{ _product.show_configurable_composition(product) }}
{% endblock pricing_content %}

Resources/views/Admin/Product/Show/general.html.twig
{% if product is variant_product %}
    {{ show_row(product.parent, 'entity', 'ekyna_product.product.field.parent', {
        'route': 'ekyna_product_product_admin_show',
        'route_params_map': {'productId': 'id'},
    }) }}
{% endif %}
{{ show_row(product.designation, 'text', 'ekyna_core.field.designation') }}
{{ show_row(product.reference, 'text', 'ekyna_core.field.reference') }}
<div class="row">
    <div class="col-md-6">
        {# TODO use IntlNumberFormatter #}
        {{ show_row(product.netPrice, 'number', 'ekyna_product.product.field.net_price', {
            'label_nb_col': 4,
            'widget_nb_col': 8,
            'append': ' €'
        }) }}
    </div>
    <div class="col-md-6">
        {{ show_row(product.taxGroup, 'entity', 'ekyna_commerce.tax_group.label.singular', {
            'route': 'ekyna_commerce_tax_group_admin_show',
            'route_params_map': {'taxGroupId': 'id'},
            'label_nb_col': 4,
            'widget_nb_col': 8
        }) }}
    </div>
</div>